Add Bangla translation for react docs
reactjs/translations.react.dev pull request #266
Opened 2023-04-25 09:36 UTC by moshfiqrony

I have been working as a software engineer for last 6 years. I have started using React since my first project in my organization.

I have added two more maintainer and both have 3+ years of working experience in React. One of them is currently a Lecture at International university of business agriculture and technology.

We are based at Bangladesh and we want to create a Bangla version of React docs for the better understanding of the Bangla native language people.

2023-04-26 16:43 UTC, moshfiqrony commented
Thank you so much @nomandhoni-cs for your interest. Can you share your previous PR link here?

2023-04-26 16:49 UTC, nomandhoni-cs commented
@moshfiqrony After making some progress, React Moved their docs from React.org to React.dev

I am pretty much involved with Open Source, as you can see from my GitHub profile. 

Merged:
https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pull/215
https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pull/216

Not Merged:
https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pull/214
https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pull/213
https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pull/205

2023-04-26 16:51 UTC, moshfiqrony commented
I really appreciate the effort. Thanks for sharing the links. I will add you.

2023-04-26 16:59 UTC, moshfiqrony commented
@nomandhoni-cs Just wanted to make sure you already saw this [Maintainer responsibilities](https://github.com/reactjs/translations.react.dev/blob/main/maintainer-guide.md#maintainer-responsibilities). If not I would encourage you to have a look at this and let me know you are ok with it.

2023-04-26 17:21 UTC, nomandhoni-cs commented
Maintainer responsibilities are almost same as previous react.org docs Maintainer responsibilities. So, I am confortable with the responsibilities

2023-04-26 18:39 UTC, nomandhoni-cs commented
Thanks, hope this PR gets merged!

2023-04-26 19:03 UTC, shakib609 commented
Hello @moshfiqrony 

Continuing from #277

Great that you took the initiative to add Bengali translations for the new website. me and @nutboltu have been mostly maintaining the previous react translations. Would love to start translating the new versions as well.

Can you kindly add me as well to the maintainers list?

You can check my previous translation PRs [here](https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pulls?q=is%3Aclosed+is%3Apr+author%3Ashakib609+).

Cheers. Looking forward to starting the new translations.

2023-04-26 19:04 UTC, ahnafyy commented
Came here from [link](https://github.com/reactjs/translations.react.dev/pull/277#issuecomment-1523883856) @moshfiqrony please add me as well as contributor!

p.s. @shakib609 would also like to be added

2023-04-26 19:04 UTC, ahnafyy commented on langs/bn.json
> +  "name": "Bangla",
Should it be 'Bengali'?

2023-04-26 19:04 UTC, ahnafyy commented on langs/bn.json
> +  "code": "bn",
bn or ben?

2023-04-26 19:40 UTC, moshfiqrony commented on langs/bn.json
> +  "name": "Bangla",
Thanks for the correction.

2023-04-26 21:10 UTC, nutboltu commented
@moshfiqrony Thanks for taking the initiative for the new translation.

I would be happy to be a part of the new journey. However, I am sharing my learnings from my previous experience:

1. It would be good to maintain a [Glossary](https://github.com/stale-reactjs-org-translations/bn.reactjs.org/wiki/Glossary) from the beginning.
2. We can set some rules for Bengali translations only. e.g
    - There shouldn't be any mixture of English and Bengali languages while translating a sentence.
    - Technical keywords shouldn't be translated.
    - A significant page can be breakdown into multiple PRs. It will help the volunteers to translate and keep updated with the changes.
3. A Slack/Discord channel for the maintainers will significantly help in further discussions.
4. Some PRs from the root repositories will require translations and fixing merge conflicts. Setting up a weekly reminder for the maintainers would help address those PRs. Otherwise, the entire translation would need to be updated.

2023-04-26 21:13 UTC, ahnafyy commented
> @moshfiqrony Thanks for taking the initiative for the new translation.
> 
> I would be happy to be a part of the new journey. However, I am sharing my learnings from my previous experience:
> 
> 1. It would be good to maintain a [Glossary](https://github.com/stale-reactjs-org-translations/bn.reactjs.org/wiki/Glossary) from the beginning.
> 2. We can set some rules for Bengali translations only. e.g
>    
>    * There shouldn't be any mixture of English and Bengali languages while translating a sentence.
>    * Technical keywords shouldn't be translated.
>    * A significant page can be breakdown into multiple PRs. It will help the volunteers to translate and keep updated with the changes.
> 3. A Slack/Discord channel for the maintainers will significantly help in further discussions.
> 4. Some PRs from the root repositories will require translations and fixing merge conflicts. Setting up a weekly reminder for the maintainers would help address those PRs. Otherwise, the entire translation would need to be updated.

1. Glossary sounds like a fantastic idea! Good call, man. Lets do it 🕺 
2. No mixture alright alright.. I see your point but can one write a sentence in bengali but keep the technical word still in english? 
3. All in for slack/discord! Lets make it.
4. Lets setup a weekend day? Maybe around bangladesh night time and US morning time? 😄

2023-04-26 21:19 UTC, nutboltu commented
@ahnafyy 
> No mixture alright alright.. I see your point but can one write a sentence in bengali but keep the technical word still in English?
IMO, we can keep the Technical keywords unchanged. (e.g.: React, Javascript, HTML, CSS). But this decision should come from all the maintainers

2023-04-27 03:55 UTC, moshfiqrony commented
@nutboltu that makes total sense. Let's continue it once the pr gets merged and the repo gets created. I have plan for Discord server for communication.

@tesseralis @gaearon Do we need to provide any more information to get this started?

2023-04-27 10:33 UTC, nafistiham commented
@moshfiqrony, I would like to join as a maintainer. [I tried contributing to react bn 4 years back](https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pull/46) Farhad Yasir vai did approve my works but unfortunately, I was a novice in using git back then and the branches got mixed up. Now I'd like to start anew.

I have more than 4 years of professional experience. Currently, I am working as a senior engineer at bKash. I have had more than 2 years of experience using React in my last workplace.  I'd like to add that I have authored a [book on mathematics](https://www.amazon.com/Gonit-Olympiad-101-somossa-somadhan/dp/B08CV5MWV9/ref=sr_1_1?qid=1682590950&refinements=p_27%3ANafis+Tiham&s=books&sr=1-1), half of which is rigorous translated work. 

I have read and understood the responsibilities. I aim to adhere to them to the best of my capability.

2023-04-27 15:05 UTC, moshfiqrony commented
@nutboltu @shakib609 @nomandhoni-cs  @ahnafyy If you guys think we should add @nafistiham as a maintainer please react with  🚀

2023-04-27 18:23 UTC, ahnafyy commented
My suggestions (i.e. opinions)

- We would like people who are familiar with actually working with react/ javascript/ know how the DOM works and have 3-4 years of experience working with it.

Reason: If not, you'll often be confused when the doc will talk about something fairly technical. If you don't truly understand what it's saying clearly you won't be able to translate it a way that remains true to its essence.

- We would like people who are actively working on it!

Reason: If not, what's the point of you being a maintainer? I am also suggesting if there are people who contribute a lot, we think about swapping them with a different person who is a maintainer and is a little inactive.

- We would like people who speak bengali and have experience translating (or skilled enough to do it!)

Reason: If you dont know how to do it haha wait what? how are you doing this? dont you dare say chatGPT or google translate lmao 🤡 

Last thought,
I say lets keep 4-5 maintainers max at first 👥 
We can swap people in and out like have a rotation if someone is being like I am going to be inactive for a bit or is wanting to move on to give someone else a chance to contribute more (or are inactive?) If you're not a maintainer when this PR gets merged that don't mean you won't be able to contribute (or even be one in the future) 😄

2023-04-27 18:28 UTC, ahnafyy commented
@gaearon here's some virtual 🍪 🍪 🍪  cookie(s) to lure you in here and get this ball rollin' 😎 🤞

🎾.......🏃🏾..🏃🏾... 💨💨

2023-04-28 08:12 UTC, moshfiqrony commented
Please join this community server https://discord.gg/ER3DzHEh

2023-04-29 03:22 UTC, gaearon requested changes
As a part of fixing the permission sync process, we've changed how we track languages — please see https://github.com/reactjs/translations.react.dev/commit/63a10c4be3f7b10ffaf58fe144e2d5abca5dacc9. 
Could you please update this PR:

- Rebase on top of latest `main`, and add the language to `lang/langs.json` instead
- Include the list of maintainers into the PR comment body instead

Thank you, and sorry for the churn.

2023-04-29 04:11 UTC, moshfiqrony commented
Thanks for the feedback @gaearon. Noted what you suggested and will update the PR accordingly.

2023-04-29 04:24 UTC, moshfiqrony commented
PR updated as described

2023-04-29 04:27 UTC, moshfiqrony commented
> As a part of fixing the permission sync process, we've changed how we track languages — please see https://github.com/reactjs/translations.react.dev/commit/63a10c4be3f7b10ffaf58fe144e2d5abca5dacc9.
Could you please update this PR:
>
> - Rebase on top of latest main, and add the language to lang/langs.json instead
> - Include the list of maintainers into the PR comment body instead
>
>Thank you, and sorry for the churn.

Thanks for the feedback @gaearon. PR Updated based on the suggestion.

**Just confirming**

- I can see langs/langs.json not lang/langs.json what you mentioned

2023-04-29 04:57 UTC, merged

2023-04-29 05:01 UTC, gaearon commented
https://github.com/reactjs/bn.react.dev/issues/1

2023-04-29 05:12 UTC, moshfiqrony commented
Thank you so much @gaearon